name: wiredbrain
description: Project by majid Hajian

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_spinkit: ^5.1.0
  flutter_svg: ^1.1.6
  font_awesome_flutter: ^10.3.0
  google_fonts: ^3.0.1
  http: ^0.13.0
  logging: ^1.1.0
  firebase_core: ^2.4.1
  firebase_analytics: ^10.1.0
  firebase_auth: ^4.2.5
  google_sign_in: "^5.0.1"
  sign_in_with_apple: ^4.3.0
  crypto: "^3.0.0"

dev_dependencies:
  flutter_launcher_icons: ^0.11.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
# run flutter pub run flutter_launcher_icons:main
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo.png"
